name: Deploy Web Content (HTML)

on:
  push:
    branches: [ main ]
    paths:
      - 'my-html-app/**'
  workflow_dispatch: {}

concurrency:
  group: webapp-content
  cancel-in-progress: true

permissions:
  contents: read

env:
  PRIVATE_MODE: 'false'   # промени на 'true' когато заключиш достъпа (PE + deny public)

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Create build marker
        run: |
          mkdir -p my-html-app
          {
            echo "repo=$GITHUB_REPOSITORY"
            echo "commit=$GITHUB_SHA"
            echo "run_id=$GITHUB_RUN_ID"
            echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          } > my-html-app/_buildinfo.txt

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: my-html-app

      # Kudu creds (за VFS проверки)
      - name: Extract Kudu credentials
        id: kudu
        if: env.PRIVATE_MODE != 'true'
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        shell: bash
        run: |
          python3 - <<'PY'
          import os, xml.etree.ElementTree as ET
          xml = os.environ['PUBLISH_PROFILE']
          root = ET.fromstring(xml)
          user = pwd = scm = None
          for p in root.findall(".//publishProfile[@publishMethod='MSDeploy']"):
              user = p.attrib.get('userName')
              pwd  = p.attrib.get('userPWD')
              url  = p.attrib.get('publishUrl')  # <app>.scm.azurewebsites.net:443
              scm  = f"https://{url.split(':')[0]}"
              break
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write(f"user={user}\n")
              f.write(f"pass={pwd}\n")
              f.write(f"scm={scm}\n")
          PY

      # Smoke 1: изчакай 200 OK на началната страница
      - name: Smoke - Wait for 200 OK
        if: env.PRIVATE_MODE != 'true'
        shell: bash
        run: |
          URL="https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net/"
          for i in {1..20}; do
            code=$(curl -k -sS -o /dev/null -w "%{http_code}" "$URL" || true)
            echo "Attempt $i -> HTTP $code"
            [ "$code" = "200" ] && exit 0
            sleep 5
          done
          echo "Site did not return 200 within the timeout."
          exit 1

      # Smoke 2: провери съдържанието на началната страница
      - name: Smoke - Check homepage content
        if: env.PRIVATE_MODE != 'true'
        shell: bash
        run: |
          URL="https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net/"
          body=$(curl -sS "$URL")
          echo "$body" | grep -qi "Practical Exam Task" || { echo "Homepage marker not found"; exit 1; }
          echo "Homepage content OK."

      # Smoke 3: провери, че index.html е качен (Kudu VFS)
      - name: Smoke - Kudu VFS index.html
        if: env.PRIVATE_MODE != 'true'
        shell: bash
        run: |
          curl -sS -u "${{ steps.kudu.outputs.user }}:${{ steps.kudu.outputs.pass }}" \
            "${{ steps.kudu.outputs.scm }}/api/vfs/site/wwwroot/index.html" -I | tee /tmp/headers.txt
          grep -q "^HTTP/.* 200" /tmp/headers.txt || { echo "index.html not found via Kudu VFS"; exit 1; }
          echo "Kudu VFS index.html OK."

      # Smoke 4: провери билд-маркера през Kudu (а не през публичния сайт)
      - name: Smoke - Kudu VFS _buildinfo.txt
        if: env.PRIVATE_MODE != 'true'
        shell: bash
        run: |
          content=$(curl -sS -u "${{ steps.kudu.outputs.user }}:${{ steps.kudu.outputs.pass }}" \
            "${{ steps.kudu.outputs.scm }}/api/vfs/site/wwwroot/_buildinfo.txt" || true)
          echo "$content"
          echo "$content" | grep -q "$GITHUB_SHA" || { echo "_buildinfo.txt missing or SHA mismatch"; exit 1; }
          echo "Kudu VFS buildinfo OK."